version: '3.5'

services:
  mysql-server:
    image: mysql:8.0
    container_name: zabbix_mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_DATABASE: zabbix
    depends_on:
      - mysql-server
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_DATABASE: zabbix
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - zabbix-network
    depends_on:
      - zabbix-server
      - mysql-server

volumes:
  mysql-data:
    driver: local
  zabbix-server-data:
    driver: local
  grafana-data:
    driver: local

networks:
  zabbix-network:
    driver: bridge
